# Generated by Django 5.0.14 on 2026-04-05 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sentiment', models.DecimalField(decimal_places=3, max_digits=4)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='programs.indicator')),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.narrative')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
    ]
